tox.ini: Add a "cover3" target
so we can look at test coverage for Python 3 separately, as there are
some definite gaps there, as evidenced by the confusion around:

- https://github.com/Pylons/venusian/pull/43
- https://github.com/Pylons/venusian/issues/44
- https://github.com/Pylons/venusian/pull/45

    [marca@marca-mac2 venusian]$ tox -e cover3
    ...
    -----------------------------------------------------------------------------------
    TOTAL                                                  1017     14    99%
    nose.plugins.cover: ERROR: TOTAL Coverage did not reach minimum required: 100%
    ERROR: InvocationError: '/Users/marca/dev/git-repos/venusian/.tox/cover3/bin/nosetests --with-xunit --with-xcoverage'
    _________________________________________________________________________________________________________________________________________________________
    summary
    __________________________________________________________________________________________________________________________________________________________
    ERROR:   cover3: commands failed